spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    #url: "jdbc:h2:mem:dev_db" ---> in memory
    url: "jdbc:h2:file:~/git/data/springKotlin"
    username: "hoda"
    password: "hoda"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect